import MenuBar from "@/components/MenuBar";
import "./globals.css";
import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.pageBackground}></div>
        <MenuBar />
        <div className="mt-[75px]">{children}</div>
      </body>
    </html>
  );
}
